version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - MONGODB_URI=mongodb+srv://domen.mihelic1@students.um.si:vojkova71@cluster0.mongodb.net/<dbname>?retryWrites=true&w=majority
    volumes:
      - .:/var/www/html
