version: '3'
services:
  app:
    build: .
    ports:
      - '80:80'
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: news
      MYSQL_USER: mendo
      MYSQL_PASSWORD: mendo
